mozilla-it/helm-charts

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/configmap.yaml
This PR will allow users using this chart to add any arbitrary environment variable to their configmaps.
This allows for more flexible and fast configuration, because now users can define extra variables without having to modify the main chart.
> Support for aribitrary environment variables

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/configmap.yaml
Previously, Helm was parsing the string adding an array to the configmap. However the app is expecting a string containing an array of strings
> Render String in configmap instead of array.

- charts/fluentd-papertrail/Chart.yaml
- charts/fluentd-papertrail/ci/ct-values.yaml
- charts/fluentd-papertrail/templates/clusterrolebinding.yaml
- charts/fluentd-papertrail/templates/daemonsets.yaml
- charts/fluentd-papertrail/templates/tests/test-secrets.yaml
- charts/fluentd-papertrail/values.yaml
- ci/ct.yaml
Had a typo for the daemonset manifest so fixing it the correct name is `DaemonSet` instead of `Daemonsets`
> Fixing a typo Daemonsets != DaemonSet

- ci/ct.yaml
The lint command's default branch is to assume its on `master`
Set the `target-branch` setting to `main` in `ct.yaml`
> Explicitly set target branch in ct.yaml file

- .travis.yml
- ci/e2e.sh
- ci/setup.sh
This PR allows to test Helm Charts which reference Container Images stored in ECR.
Before this, when the chart was end-to-end tested, and the container image was stored in ECR, the test were failing because the "kind" cluster didn't have enough permissions to pull the image.
This changes leverages the standard Kubernetes way of pasing this kind of credentials, which is using a secret file. More on this in the [official documentation](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod).
From here on, pulling from ECR is possible adding specifying the name of the secret in your chart/ci folder. For mozmoderator chart, it goes like this:
```
cat mozmoderator/ci/test-values.yaml 
imagePullSecrets:
- name: ecr-registry 
```
> Allow Travis to Pull Containers from ECR

- charts/refractr/Chart.yaml
- charts/refractr/templates/_helpers.tpl
- charts/refractr/templates/ingress-hook.yaml
This sets consistent labels across all resources that `refractr` uses
> Add consistent labels for refractr helm charts

- charts/fluentd-papertrail/Chart.yaml
- charts/mozilla-common-voice/Chart.lock
- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/ingress.yaml
- charts/mozilla-common-voice/values.yaml
After updating helm in PR #53 it appears that lints are failing because of certain `apiVersion` has been deprecated. This PR resolves some of the errors based on the errors that `helm lint` is throwing as well as fixing some deprecated api's
See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more info
> Fixing charts to make it pass helm lints

- charts/refractr/Chart.yaml
- charts/refractr/templates/deployment.yaml
- charts/refractr/values.yaml
Also making this a bit smarter, if we're making the metrics pod let's scrape it
And use the same port as what's exposed by the pod
> Moving annotations from deployment to the pod level.

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/configmap.yaml
@The-smooth-operator I've left the BUCKET_NAME in there for now just for backwards compatibility, assuming the changes to accommodate old datasets won't be ready concurrently on all environments.
> Add dataset bucket to config-map also

- charts/ctms/Chart.yaml
- charts/ctms/templates/NOTES.txt
- charts/ctms/templates/db-migration.yaml
- charts/ctms/templates/secrets.yaml
adds a job that runs on each install and each upgrade
uses the same image as the deployment
makes secrets accessible in the hook
> Adding a db-migration

- charts/configmapsecrets/Chart.yaml
- charts/configmapsecrets/templates/customresourcedefinition.yaml
- charts/configmapsecrets/templates/deployment.yaml
- charts/configmapsecrets/templates/rolebindings.yaml
- charts/configmapsecrets/templates/roles.yaml
- charts/configmapsecrets/templates/service.yaml
- charts/configmapsecrets/templates/serviceaccount.yaml
To allow deployment of this tool, which is useful for configs that have
very little secret content, but need that secret content to be in line.
> Initial version of the configmapsecrets helm chart

- charts/prometheus-customizations/Chart.yaml
- charts/prometheus-customizations/templates/influx-secret.yml
- charts/prometheus-customizations/values.yaml
Secrets have key/name and property to correctly go to aws secrets manager and get all the info stored correctly.
> Adding a property to access key in dict

- charts/ctms/Chart.yaml
- charts/ctms/templates/background_deployment.yaml
- charts/ctms/templates/service.yaml
- charts/ctms/templates/web_deployment.yaml
This is a first cut at this, still needs some extra work but wanted to get something up now for a first review.
My thinking was that this is basically the same as the deployment that was there already but without some things that only make sense for pods exposing ports. I updated the selectors so that the service should expose the web deployment but not the background one.
It's been a bit since I did something like this so feel free to tell me to trash this whole thing and start again.
> Add a background job deployment for ctms

- charts/ctms/Chart.yaml
- charts/ctms/ci/test-values.yaml
- charts/ctms/templates/db-migration.yaml
- charts/ctms/templates/secrets.yaml
- ci/deps/ctms/install.sh
- ci/deps/install.sh
- ci/e2e.sh
Trying to get the existing pipeline back to green by making ctms helm chart install correctly.
Installing postgres to the cluster for ephemeral testing of the db migration.
Added a new dependency installation pattern to this pipeline to be able to install postgres.
Updated secrets to include new values.
> Fixing up the helm chart pipeline for ctms

- charts/pastebin/Chart.yaml
- charts/pastebin/templates/deployment.yaml
- charts/pastebin/templates/job.yaml
In furtherance of https://mozilla-hub.atlassian.net/browse/SE-1152 (formerly SE-1993)
Get rid of a stray - causing some havoc in a pastebin conditional block added for local dev env support.
> dumb yaml error in pastebin secret conditional

- charts/mozmoderator/Chart.yaml
- charts/mozmoderator/templates/deployment.yaml
Jira: Came up in context of pastebin & mozmoderator helm charts
* changes mozmoderator maintainers to just say Web SRE team & include the it-sre@mozilla.com email - breaking into multiple PRs bc all the charts updated at once broke Travis (again).
* removes dev.sh args from deployment (runs with logs showing in container as opposed to wsgi)
> update mozmoderator chart to not default to dev args, maintainer=team

- CODEOWNERS
Jira: none, came up in context of other PRs
* removes CodeOwners file, which was causing @mozilla-it/it-se (or a random member of that team) to appear as a reviewer on helm chart PRs even if deselected in PR creation
* IT-SE has a lot of people on it that don't interact with helm charts, and there are new folks (@mozilla-it/sumo-devs) starting to at least review work here more that aren't on IT-SE team, so seems best to me to just remove it
> remove codeowners from helm charts repo

- charts/mozmoderator/Chart.yaml
- charts/mozmoderator/README.md
- charts/mozmoderator/ci/test-values.yaml
- charts/mozmoderator/values.yaml
Jira: none, came up in context of https://mozilla-hub.atlassian.net/browse/SE-2166
* Upticks Moderator Chart version to make CI happy (we use a very opinionated tool for Helm Chart ci - https://github.com/helm/chart-testing - that expects chart version upticks whenever changes occur to a chart)
* removes comment references to expected MOZILLIANS_API_* secrets available in the chart runtime (these comments are left to help guide leave breadcrumbs for the state of secrets)
* removes MOZILLIANS_API_* configMap variables for the CI test-values.yaml
* updates default image tag for deployment to commit / tag ﻿﻿bbae8c1be8431ace923c58caac928917fc2aa31e (what is used in current production)
> remove references to MOZILLA_API variables, uptick moderator chart

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/deployment.yaml
- charts/mozilla-common-voice/values.yaml
Jira ticket: https://mozilla-hub.atlassian.net/browse/SE-2416
- adds imagePullSecrets secret field to common voice web deployment template
- can create docker secret in k8s out of band, this is a (harmless) temporary measure to test a hypothesis around flux docker image pull failures
> add imagePullSecrets in common voice web deploy template

- charts/discourse/Chart.yaml
- charts/discourse/templates/deployment.yaml
- charts/discourse/values.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-2169
* Removes `iam.amazonaws.com/role` value from the Discourse application helm chart
* we're doing this because it expects kube2iam, which isn't a given on new EKS clusters
> update discourse helm chart to not use kubeiam arn-role annotation

- charts/etherpad/.helmignore
- charts/etherpad/Chart.lock
- charts/etherpad/Chart.yaml
- charts/etherpad/ci/test-values.yaml
- charts/etherpad/templates/_helpers.tpl
- charts/etherpad/templates/configmap.yaml
- charts/etherpad/templates/deployment.yaml
- charts/etherpad/templates/ingress.yaml
- charts/etherpad/templates/issuer.yaml
- charts/etherpad/templates/job.yaml
- charts/etherpad/templates/secrets.yaml
- charts/etherpad/templates/service.yaml
- charts/etherpad/templates/tests/test-connection.yaml
- charts/etherpad/values.yaml
- charts/oidc-gateway/.helmignore
- charts/oidc-gateway/Chart.yaml
- charts/oidc-gateway/README.md
- charts/oidc-gateway/ci/test-values.yaml
- charts/oidc-gateway/templates/NOTES.txt
- charts/oidc-gateway/templates/_helpers.tpl
- charts/oidc-gateway/templates/configmap.yaml
- charts/oidc-gateway/templates/deployment.yaml
- charts/oidc-gateway/templates/ingress.yaml
- charts/oidc-gateway/templates/secrets.yaml
- charts/oidc-gateway/templates/service.yaml
- charts/oidc-gateway/values.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-1151
* Creates a Helm Chart for oidc-gateway (see https://github.com/mozilla-services/oidc-gateway), used by Etherpad but deployed manually using helm v1 template before
* Creates a Helm Chart for Etherpad, which expects in our implementation (but doesn't explicitly require as a dependency) oidc-gateway
> helm charts for oidc-gateway & etherpad

- charts/careers/.helmignore
- charts/careers/Chart.yaml
- charts/careers/ci/test-values.yaml
- charts/careers/templates/NOTES.txt
- charts/careers/templates/_helpers.tpl
- charts/careers/templates/configmap.yaml
- charts/careers/templates/db-migration.yaml
- charts/careers/templates/hpa.yaml
- charts/careers/templates/ingress.yaml
- charts/careers/templates/periodic_job.yaml
- charts/careers/templates/secrets.yaml
- charts/careers/templates/service.yaml
- charts/careers/templates/serviceaccount.yaml
- charts/careers/templates/tests/test-connection.yaml
- charts/careers/templates/web_deployment.yaml
- charts/careers/values.yaml
- ci/deps/careers/install.sh
Initial helm chart for careers
DB migration as preinstall hook
then generates a webdeployment, with service and nginx ingress to server the traffic
also creates a cronjob, to pull job data from greenhouse and push the static version of the website to s3 as well
> initial commit of careers

- charts/securitywiki/.helmignore
- charts/securitywiki/Chart.lock
- charts/securitywiki/Chart.yaml
- charts/securitywiki/ci/test-values.yaml
- charts/securitywiki/templates/_helpers.tpl
- charts/securitywiki/templates/configmap.yaml
- charts/securitywiki/templates/deployment.yaml
- charts/securitywiki/templates/hpa.yaml
- charts/securitywiki/templates/ingress.yaml
- charts/securitywiki/templates/issuer.yaml
- charts/securitywiki/templates/pv.yaml
- charts/securitywiki/templates/pvc.yaml
- charts/securitywiki/templates/secrets.yaml
- charts/securitywiki/templates/service.yaml
- charts/securitywiki/values.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-1153
* creates a first pass of a securitywiki helm chart, with some pretty big overrides for CI to pass (biggest one of these overrides is that we can't use our securitywiki image to test the chart, since our image has Apache setup with OIDC, so the pod won't run without a valid OIDC connection - which I don't want to setup in CI).
> first pass of securitywiki helm chart

- README.md
Jira: not related to any tickets, just noticed failing badge on readme
> update readme.md with GHA badge instead of travis

- charts/github-actions-runner/.helmignore
- charts/github-actions-runner/Chart.yaml
- charts/github-actions-runner/ci/ct-values.yaml
- charts/github-actions-runner/templates/_helpers.tpl
- charts/github-actions-runner/templates/configmap.yaml
- charts/github-actions-runner/templates/deployment.yaml
- charts/github-actions-runner/values.yaml
Jira: https://mozilla-hub.atlassian.net/browse/OPST-164
* adds start of a helm chart for GitHub Actions self-hosted runners
Not included:
* mainly setting up now for use in our global terraform atlantis deployments.
> add starter helm chart for github action runners

- charts/prometheus-customizations/Chart.yaml
- charts/prometheus-customizations/templates/prometheus_config.yml
- charts/prometheus-customizations/values.yaml
not needed with the ability to pass recording rules directly to the community prometheus chart
> Revert "You can now inject recording rules into our helm chart (#127)"

- charts/github-actions-runner/Chart.yaml
- charts/github-actions-runner/templates/deployment.yaml
- charts/github-actions-runner/values.yaml
See #128 
This PR just makes the deployment's SecurityContext configuration configurable outside of the helm chart templates.
> make securitycontext configurable

- charts/ctms/Chart.yaml
- charts/ctms/templates/ingress.yaml
- charts/fluentd-papertrail/Chart.yaml
- charts/fluentd-papertrail/templates/daemonsets.yaml
- charts/fluentd-papertrail/values.yaml
- Fluent has moved images to Dockerhub. They are no longer publishing "Papertrail" versions but this gets us a much newer release non the less. The UID change is to give the pod access to tail the logs, without that it was failing.
- Ingress beta1 migrated to v1 as of 1.19
> chore(helm): Updates

- charts/pastebin/Chart.yaml
- charts/pastebin/templates/secrets.yaml
- charts/pastebin/values.yaml
This migrates to new external-secrets operator from deprecated
external-secrets helm service.
This will need to contain a change in the
`k8s/releases/pastebin/pastebin.yaml` in order to complete the
migration.
I have a diff like the following queued up for the itse-stage environment. These changes should conform to the new (external-secrets-operator API)[https://external-secrets.io/v0.5.9/api-externalsecret/].
```diff
diff --git a/k8s/releases/pastebin/pastebin.yaml b/k8s/releases/pastebin/pastebin.yaml
index 61455f3..db6bded 100644
--- a/k8s/releases/pastebin/pastebin.yaml
+++ b/k8s/releases/pastebin/pastebin.yaml
@@ -28,21 +28,26 @@ spec:
enabled: true
name: pastebin
secrets:
-      - key: /stage/pastebin/envvar
-        name: DB_HOST
-        property: database_host
-      - key: …
```
> feature(external-secrets): Migrate to new external-secrets
