mozilla-it/helm-charts

- charts/data-alert-sender/.helmignore
- charts/data-alert-sender/Chart.yaml
- charts/data-alert-sender/templates/_helpers.tpl
- charts/data-alert-sender/templates/cronjob.yaml
- charts/data-alert-sender/values.yaml
not entirely sure if I'm doing this correctly but the stakes are low :) @limed a review please
> possibly adding a helm chart

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/deployment.yaml
See https://github.com/helm/helm/issues/3854 for more information
> [mozilla-common-voice] indent has rendering issues

- charts/mozalert-controller/.helmignore
- charts/mozalert-controller/Chart.yaml
- charts/mozalert-controller/crds/crd.yaml
- charts/mozalert-controller/templates/_helpers.tpl
- charts/mozalert-controller/templates/clusterrole.yaml
- charts/mozalert-controller/templates/clusterrolebinding.yaml
- charts/mozalert-controller/templates/service.yaml
- charts/mozalert-controller/templates/serviceaccount.yaml
- charts/mozalert-controller/templates/stateful.yaml
- charts/mozalert-controller/templates/tests/test-controller.yaml
- charts/mozalert-controller/values.yaml
Adding mozalert helm chart. Canonical location is https://github.com/mozilla-it/mozalert/tree/main/charts/mozalert-controller
> adding mozalert chart

- .travis.yml
- README.md
> Rename references master to main

- charts/sentence-collector/.helmignore
- charts/sentence-collector/Chart.lock
- charts/sentence-collector/Chart.yaml
- charts/sentence-collector/templates/NOTES.txt
- charts/sentence-collector/templates/_helpers.tpl
- charts/sentence-collector/templates/deployment.yaml
- charts/sentence-collector/templates/hpa.yaml
- charts/sentence-collector/templates/ingress.yaml
- charts/sentence-collector/templates/secret.yaml
- charts/sentence-collector/templates/service.yaml
- charts/sentence-collector/templates/serviceaccount.yaml
- charts/sentence-collector/templates/tests/test-connection.yaml
- charts/sentence-collector/values.yaml
This PR creates a Helm Chart for Sentence Collector.
Sentence Collector is part of Mozilla's Voice initiative. Using the application users can submit sentences which, after vetting them, will be incorporated into Common Voice for other users to read them.
This Chart is expected to be used in the voice cluster as well as by the community who help with the development of the tool
> [sentence-collector] Create new Chart for Voice Sentence Collector

- charts/mozilla-common-voice/Chart.yaml
- charts/mozilla-common-voice/templates/ingress.yaml
- charts/mozilla-common-voice/values.yaml
> [mozilla-common-voice] Add support for listening in multiple domains

- charts/refractr/Chart.yaml
- charts/refractr/templates/le-issuer.yaml
- charts/refractr/templates/secrets.yaml
- charts/refractr/values.yaml
- removed '$'
- humpCased 'externalSecret'
- 'issuer.yaml' -> 'le-issuer.yaml' to avoid name collision
> made adjustments|fixes to refractr chart

- charts/refractr/Chart.yaml
- charts/refractr/README.md
This PR updates references to main branch
> [refractr] Update references to main branch

- charts/refractr/Chart.yaml
- charts/refractr/templates/hpa.yaml
- charts/refractr/values.yaml
- ci/kind.yaml
Add HPA support for refractr pods
> Add HPA support for refractr helm chart

- charts/refractr/Chart.yaml
- charts/refractr/templates/deployment.yaml
- charts/refractr/values.yaml
Adding resource limits to refractr helm chart
> Add resources to refractr

- charts/refractr/Chart.yaml
- charts/refractr/values.yaml
> [refractr] specify resources for metrics container;

- charts/refractr/Chart.yaml
- charts/refractr/templates/ingress-hook.yaml
- charts/refractr/values.yaml
Hopefully if fixes HPA for good. HPA is not working when detecting containers with no requests and limits specified
> [refractr] Specify resources for preinstall-hook;

- charts/mozalert-controller/Chart.yaml
- charts/mozalert-controller/crds/crd.yaml
Adding a text/link field to escalations, to make it easier to link runbooks/source code
in escalations
> Adding a new reference argument to our chart

- charts/mentoring/Chart.yaml
- charts/mentoring/templates/configmap.yaml
- charts/mentoring/values.yaml
The app is not generating this correctly, so we want to be able to set
it explicitly.
https://jira.mozilla.com/browse/SE-1483
> Mentoring: Support setting OIDC callback url

- charts/prometheus-customizations/Chart.yaml
- charts/prometheus-customizations/templates/influx-secret.yml
- charts/prometheus-customizations/templates/prometheus_config.yml
- charts/prometheus-customizations/values.yaml
Is a way to connect to influxdb directly, basically just creating a secret -> configmapsecret -> secret for prom to use
> Adding a helm chart for an opinionated prom setup

- charts/pastebin/.helmignore
- charts/pastebin/Chart.lock
- charts/pastebin/Chart.yaml
- charts/pastebin/ci/test-values.yaml
- charts/pastebin/templates/_helpers.tpl
- charts/pastebin/templates/configmap.yaml
- charts/pastebin/templates/deployment.yaml
- charts/pastebin/templates/ingress.yaml
- charts/pastebin/templates/issuer.yaml
- charts/pastebin/templates/job.yaml
- charts/pastebin/templates/secrets.yaml
- charts/pastebin/templates/service.yaml
- charts/pastebin/templates/tests/test-connection.yaml
- charts/pastebin/values.yaml
Jira ticket: https://mozilla-hub.atlassian.net/browse/SE-1152
* sets up a Pastebin helm chart in preparation for moving this application between k8s clusters
Note: this has been tested on local and non-prod EKS cluster deploys, though I'm sure there will be future PRs with some configuration changes and updates as this moves closer to prod.
> first draft of pastebin helm chart

- charts/data-alert-sender/Chart.yaml
see previous PRs where travis broke.
> update data-alert-sender chart to maintainer=team

- charts/fluentd-papertrail/Chart.yaml
see previous prs that broke travis
> update fluentd-papertrail chart to maintainer=team

- charts/mozilla-common-voice/Chart.yaml
see previous PRs that broke travis
> update mozilla-common-voice chart to maintainer=team

- charts/pastebin/Chart.yaml
see previous PRs that broke travis
> update pastebin chart to maintainer=team

- charts/refractr/Chart.yaml
- charts/refractr/templates/ingress-hook.yaml
see previous PRs that failed due to travis
> update refractr chart to maintainer=team, replace rbac.authorization.k8s.io/v1beta1/Role*

- charts/sentence-collector/Chart.yaml
see previous PRs where travis failed
> update sentence-collector chart to maintainer=team

- charts/discourse/.helmignore
- charts/discourse/Chart.lock
- charts/discourse/Chart.yaml
- charts/discourse/README.md
- charts/discourse/ci/test-values.yaml
- charts/discourse/templates/NOTES.txt
- charts/discourse/templates/_helpers.tpl
- charts/discourse/templates/configmap.yaml
- charts/discourse/templates/db-jobs.yaml
- charts/discourse/templates/deployment.yaml
- charts/discourse/templates/hpa.yaml
- charts/discourse/templates/ingress.yaml
- charts/discourse/templates/issuer.yaml
- charts/discourse/templates/secrets.yaml
- charts/discourse/templates/service.yaml
- charts/discourse/values.yaml
- ci/deps/discourse/install.sh
Jira: https://mozilla-hub.atlassian.net/browse/SE-1149
* Creates a first draft of a Discourse Helm Chart PR (replacing the kubernetes manifests in the discourse application & infra codebases)
* Adds CI steps for installing postgres & redis for discourse CI
> first draft of discourse chart

- charts/discourse/Chart.yaml
- charts/discourse/templates/logger-config.yaml
See #121 - I just inverted key & name in the externalsecrets spec.
> i did a stupid on discourse helm chart

- .github/workflows/ci.yaml
- charts/prometheus-customizations/Chart.yaml
- charts/prometheus-customizations/templates/prometheus_config.yml
- charts/prometheus-customizations/values.yaml
This is useful for boiling down very complex queries into easier to read simple queries
and was needed now for ctms - need to be able to compare a few numbers and it's easier with this method
> You can now inject recording rules into our helm chart

- .github/workflows/ci.yaml
- charts/mozmoderator/Chart.lock
- charts/mozmoderator/Chart.yaml
- charts/mozmoderator/README.md
- charts/mozmoderator/templates/pdb.yaml
- charts/mozmoderator/values.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget for mozmoderator app on k8s to be upgraded, update CI tests.
Also updated the CI tests to rely on current and target kubernetes versions.
> Add PodDisruptionBudget for mozmoderator app on k8s to be upgraded, update CI tests.

- charts/pastebin/Chart.lock
- charts/pastebin/Chart.yaml
- charts/pastebin/ci/test-values.yaml
- charts/pastebin/templates/job.yaml
- charts/pastebin/templates/pdb.yaml
- charts/pastebin/values.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget for pastebin app on k8s to be upgraded.
> Add PodDisruptionBudget for pastebin

- charts/etherpad/Chart.lock
- charts/etherpad/Chart.yaml
- charts/etherpad/templates/job.yaml
- charts/etherpad/templates/pdb.yaml
- charts/etherpad/values.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget for etherpad app on k8s to be upgraded.
> Add PodDisruptionBudget for etherpad

- charts/refractr/Chart.lock
- charts/refractr/Chart.yaml
- charts/refractr/templates/pdb.yaml
- charts/refractr/values.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget for refractr app on k8s to be upgraded.
> Add PodDisruptionBudget for refractr

- charts/etherpad/Chart.yaml
- charts/etherpad/templates/secrets.yaml
- charts/etherpad/values.yaml
Migrate etherpad to new external-secrets-operator API.
> feature(etherpad): Migrate to new external-secrets operator API
